version: '3.8'

services:
  flask_app:
    image: whilter_flask_flask_app
    command: flask run --host=0.0.0.0 --port=5001
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    depends_on:
      - redis
    networks:
      - whilter_network

  redis:
    image: redis:7.0.6
    ports:
      - "6379:6379"
    networks:
      - whilter_network

  celery:
    image: whilter_flask_flask_app
    command: celery -A app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - whilter_network

networks:
  whilter_network:
    driver: bridge

